general.import = [
  "themes/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 20
padding.y = 20

decorations = "Buttonless"
opacity = 0.95
blur = true
startup_mode = "Maximized"

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 12.0

[selection]
save_to_clipboard = true

[cursor.style]
shape = "Block"
blinking = "Off"
