general.import = [
  "themes/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 20
padding.y = 20

decorations = "Buttonless"
opacity = 0.70
blur = true

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 12.0

[selection]
save_to_clipboard = true

[cursor.style]
shape = "Beam"
blinking = "Off"
