general:
  startup_commands: []
  shutdown_commands: []
  config_reload_commands: []
  focus_follows_cursor: false
  toggle_workspace_on_refocus: false

  cursor_jump:
    enabled: true
    trigger: "monitor_focus"

  hide_method: "cloak"

  show_all_in_taskbar: false

gaps:
  # Whether to scale the gaps with the DPI of the monitor.
  scale_with_dpi: true

  # Gap between adjacent windows.
  inner_gap: "0px"

  # Gap between windows and the screen edge.
  outer_gap:
    top: "0px"
    right: "0px"
    bottom: "0px"
    left: "0px"

window_effects:
  # Visual effects to apply to the focused window.
  focused_window:
    # Highlight the window with a colored border.
    # ** Exclusive to Windows 11 due to API limitations.
    border:
      enabled: true
      color: "#582ba8"

    # Remove the title bar from the window's frame. Note that this can
    # cause rendering issues for some applications.
    hide_title_bar:
      enabled: false

    # Change the corner style of the window's frame.
    # ** Exclusive to Windows 11 due to API limitations.
    corner_style:
      enabled: true
      # Allowed values: 'square', 'rounded', 'small_rounded'.
      style: "square"

    # Change the transparency of the window.
    transparency:
      enabled: false
      # Can be something like '95%' or '0.95' for slightly transparent windows.
      opacity: "95%"

  # Visual effects to apply to non-focused windows.
  other_windows:
    border:
      enabled: false
      color: "#a1a1a1"
    hide_title_bar:
      enabled: false
    corner_style:
      enabled: true
      style: "square"
    transparency:
      enabled: false
      opacity: "95%"

window_behavior:
  # New windows are created in this state whenever possible.
  # Allowed values: 'tiling', 'floating'.
  initial_state: "tiling"

  # Sets the default options for when a new window is created. This also
  # changes the defaults for when the state change commands, like
  # `set-floating`, are used without any flags.
  state_defaults:
    floating:
      # Whether to center floating windows by default.
      centered: true

      # Whether to show floating windows as always on top.
      shown_on_top: false

    fullscreen:
      # Maximize the window if possible. If the window doesn't have a
      # maximize button, then it'll be fullscreen'ed normally instead.
      maximized: true

      # Whether to show fullscreen windows as always on top.
      shown_on_top: false

workspaces:
  - name: "1"
  - name: "2"
  - name: "3"
  - name: "4"
  - name: "5"
  - name: "6"
  - name: "7"
  - name: "8"
  - name: "9"

window_rules:
  - commands: ["ignore"]
    match:
      # Ignores picture-in-picture windows for browsers.
      - window_title: { regex: "[Pp]icture.in.[Pp]icture" }
        window_class: { regex: "Chrome_WidgetWin_1|MozillaDialogClass" }

      # Ignore rules for various 3rd-party apps.
      - window_process: { equals: "PowerToys" }
        window_class: { regex: 'HwndWrapper\[PowerToys\.PowerAccent.*?\]' }
      - window_process: { equals: "PowerToys" }
        window_title: { regex: ".*? - Peek" }
      - window_process: { equals: "Lively" }
        window_class: { regex: "HwndWrapper" }
  # Workspace 1
  - commands: ["move --workspace 1"]
    match:
      - window_process: { equals: "firefox" }
  - commands: ["move --workspace 1"]
    match:
      - window_process: { equals: "chrome" }
  - commands: ["move --workspace 1"]
    match:
      - window_process: { equals: "msedge" }
  - commands: ["move --workspace 1"]
    match:
      - window_process: { equals: "zen" }

  # Workspace 2
  - commands: ["move --workspace 2"]
    match:
      - window_process: { equals: "Code" }
  - commands: ["move --workspace 2"]
    match:
      - window_process: { equals: "Zed" }
  # Workspace 3
  - commands: ["move --workspace 3"]
    match:
      - window_process: { equals: "WindowsTerminal" }
  - commands: ["move --workspace 3"]
    match:
      - window_process: { equals: "alacritty" }

  # Workspace 4
  - commands: ["move --workspace 4"]
    match:
      - window_process: { equals: "Ssms" }
  - commands: ["move --workspace 4"]
    match:
      - window_process: { equals: "notepad++" }
  - commands: ["move --workspace 4"]
    match:
      - window_process: { equals: "explorer" }

  # Workspace 5
  - commands: ["move --workspace 5"]
    match:
      - window_process: { equals: "Telegram" }
  - commands: ["move --workspace 5"]
    match:
      - window_process: { equals: "Signal" }

  # Workspace 6
  - commands: ["move --workspace 6"]
    match:
      - window_process: { equals: "Obsidian" }

  # Workspace 7
  - commands: ["move --workspace 7"]
    match:
      - window_process: { equals: "rider64" }
  - commands: ["move --workspace 7"]
    match:
      - window_process: { equals: "devenv" }

  # Workspace 8
  - commands: ["move --workspace 8"]
    match:
      - window_process: { equals: "slack" }
  - commands: ["move --workspace 8"]
    match:
      - window_process: { equals: "ms-teams" }

binding_modes:
  - name: "resize"
    keybindings:
      - commands: ["resize --width -2%"]
        bindings: ["h", "left"]
      - commands: ["resize --width +2%"]
        bindings: ["l", "right"]
      - commands: ["resize --height +2%"]
        bindings: ["k", "up"]
      - commands: ["resize --height -2%"]
        bindings: ["j", "down"]
      # Press enter/escape to return to default keybindings.
      - commands: ["wm-disable-binding-mode --name resize"]
        bindings: ["escape", "enter"]

keybindings:
  # Shift focus in a given direction.
  - commands: ["focus --direction left"]
    bindings: ["lwin+h", "lwin+left"]
  - commands: ["focus --direction right"]
    bindings: ["lwin+l", "lwin+right"]
  - commands: ["focus --direction up"]
    bindings: ["lwin+k", "lwin+up"]
  - commands: ["focus --direction down"]
    bindings: ["lwin+j", "lwin+down"]

  # Move focused window in a given direction.
  - commands: ["move --direction left"]
    bindings: ["lwin+shift+h", "lwin+shift+left"]
  - commands: ["move --direction right"]
    bindings: ["lwin+shift+l", "lwin+shift+right"]
  - commands: ["move --direction up"]
    bindings: ["lwin+shift+k", "lwin+shift+up"]
  - commands: ["move --direction down"]
    bindings: ["lwin+shift+j", "lwin+shift+down"]

  # As an lwinernative to the resize keybindings above, resize mode enables
  # resizing via arrow keys or HJKL. The binding mode is defined above with
  # the name 'resize'.
  - commands: ["wm-enable-binding-mode --name resize"]
    bindings: ["lwin+r"]

  # Disables window management and all other keybindings until lwin+shift+p
  # is pressed again.
  - commands: ["wm-toggle-pause"]
    bindings: ["lwin+shift+p"]

  # Change tiling direction. This determines where new tiling windows will
  # be inserted.
  - commands: ["toggle-tiling-direction"]
    bindings: ["lwin+v"]

  # Change focus from tiling windows -> floating -> fullscreen.
  - commands: ["wm-cycle-focus"]
    bindings: ["lwin+space"]

  # Change the focused window to be floating.
  - commands: ["toggle-floating --centered"]
    bindings: ["lwin+shift+space"]

  # Change the focused window to be tiling.
  - commands: ["toggle-tiling"]
    bindings: ["lwin+t"]

  # Change the focused window to be fullscreen.
  - commands: ["toggle-fullscreen"]
    bindings: ["lwin+f"]

  # Minimize focused window.
  - commands: ["toggle-minimized"]
    bindings: ["lwin+m"]

  # Close focused window.
  - commands: ["close"]
    bindings: ["lwin+shift+q"]

  # Kill GlazeWM process safely.
  - commands: ["wm-exit"]
    bindings: ["lwin+shift+e"]

  # Re-evaluate configuration file.
  - commands: ["wm-reload-config"]
    bindings: ["lwin+shift+r"]

  # Redraw all windows.
  - commands: ["wm-redraw"]
    bindings: ["lwin+shift+w"]

  # Launch CMD terminal. lwinernatively, use `shell-exec wt` or
  # `shell-exec %ProgramFiles%/Git/git-bash.exe` to start Windows
  # Terminal and Git Bash respectively.
  - commands: ["shell-exec alacritty"]
    bindings: ["lwin+enter"]

  # Focus the next/previous active workspace defined in `workspaces` config.
  - commands: ["focus --next-active-workspace"]
    bindings: ["lwin+s"]
  - commands: ["focus --prev-active-workspace"]
    bindings: ["lwin+a"]

  # Focus the workspace that last had focus.
  - commands: ["focus --recent-workspace"]
    bindings: ["lwin+d"]

  # Change focus to a workspace defined in `workspaces` config.
  - commands: ["focus --workspace 1"]
    bindings: ["lwin+1"]
  - commands: ["focus --workspace 2"]
    bindings: ["lwin+2"]
  - commands: ["focus --workspace 3"]
    bindings: ["lwin+3"]
  - commands: ["focus --workspace 4"]
    bindings: ["lwin+4"]
  - commands: ["focus --workspace 5"]
    bindings: ["lwin+5"]
  - commands: ["focus --workspace 6"]
    bindings: ["lwin+6"]
  - commands: ["focus --workspace 7"]
    bindings: ["lwin+7"]
  - commands: ["focus --workspace 8"]
    bindings: ["lwin+8"]
  - commands: ["focus --workspace 9"]
    bindings: ["lwin+9"]

  # Move the focused window's parent workspace to a monitor in a given
  # direction.
  - commands: ["move-workspace --direction left"]
    bindings: ["lwin+shift+a"]
  - commands: ["move-workspace --direction right"]
    bindings: ["lwin+shift+f"]
  - commands: ["move-workspace --direction up"]
    bindings: ["lwin+shift+d"]
  - commands: ["move-workspace --direction down"]
    bindings: ["lwin+shift+s"]

  # Move focused window to a workspace defined in `workspaces` config.
  - commands: ["move --workspace 1", "focus --workspace 1"]
    bindings: ["lwin+shift+1"]
  - commands: ["move --workspace 2", "focus --workspace 2"]
    bindings: ["lwin+shift+2"]
  - commands: ["move --workspace 3", "focus --workspace 3"]
    bindings: ["lwin+shift+3"]
  - commands: ["move --workspace 4", "focus --workspace 4"]
    bindings: ["lwin+shift+4"]
  - commands: ["move --workspace 5", "focus --workspace 5"]
    bindings: ["lwin+shift+5"]
  - commands: ["move --workspace 6", "focus --workspace 6"]
    bindings: ["lwin+shift+6"]
  - commands: ["move --workspace 7", "focus --workspace 7"]
    bindings: ["lwin+shift+7"]
  - commands: ["move --workspace 8", "focus --workspace 8"]
    bindings: ["lwin+shift+8"]
  - commands: ["move --workspace 9", "focus --workspace 9"]
    bindings: ["lwin+shift+9"]
